#
# From ${D}/test/unittests/BUILD.gn
#

set(D ${PROJECT_SOURCE_DIR}/v8/test/unittests)

add_library(cppgc_unittests_sources OBJECT
  ${D}/heap/cppgc/concurrent-sweeper-unittest.cc
  ${D}/heap/cppgc/custom-spaces-unittest.cc
  ${D}/heap/cppgc/finalizer-trait-unittest.cc
  ${D}/heap/cppgc/free-list-unittest.cc
  ${D}/heap/cppgc/garbage-collected-unittest.cc
  ${D}/heap/cppgc/gc-info-unittest.cc
  ${D}/heap/cppgc/gc-invoker-unittest.cc
  ${D}/heap/cppgc/heap-growing-unittest.cc
  ${D}/heap/cppgc/heap-object-header-unittest.cc
  ${D}/heap/cppgc/heap-page-unittest.cc
  ${D}/heap/cppgc/heap-unittest.cc
  ${D}/heap/cppgc/logging-unittest.cc
  ${D}/heap/cppgc/marker-unittest.cc
  ${D}/heap/cppgc/marking-visitor-unittest.cc
  ${D}/heap/cppgc/member-unittest.cc
  ${D}/heap/cppgc/minor-gc-unittest.cc
  ${D}/heap/cppgc/object-start-bitmap-unittest.cc
  ${D}/heap/cppgc/page-memory-unittest.cc
  ${D}/heap/cppgc/persistent-unittest.cc
  ${D}/heap/cppgc/prefinalizer-unittest.cc
  ${D}/heap/cppgc/source-location-unittest.cc
  ${D}/heap/cppgc/stack-unittest.cc
  ${D}/heap/cppgc/stats-collector-unittest.cc
  ${D}/heap/cppgc/sweeper-unittest.cc
  ${D}/heap/cppgc/test-platform.cc
  ${D}/heap/cppgc/test-platform.h
  ${D}/heap/cppgc/tests.cc
  ${D}/heap/cppgc/tests.h
  ${D}/heap/cppgc/visitor-unittest.cc
  ${D}/heap/cppgc/worklist-unittest.cc
  ${D}/heap/cppgc/write-barrier-unittest.cc
  )
target_config(cppgc_unittests_sources
  PRIVATE
    v8_features
    v8_disable_exceptions
    external_config
    internal_config_base
    cppgc_base_config
  )
target_compile_options(cppgc_unittests_sources
  PRIVATE
    $<${is-clang}:-Wno-narrowing>
  )
target_link_libraries(cppgc_unittests_sources
  PUBLIC
    gmock gtest
  #PRIVATE
  #  cppgc_for_testing
  )

#add_dependencies(cppgc_unittests_sources
#  cppgc_for_testing
#  )

add_executable(cppgc_unittests
  ${D}/heap/cppgc/run-all-unittests.cc
  $<TARGET_OBJECTS:cppgc_unittests_sources>
  $<TARGET_OBJECTS:v8_cppgc_shared>
  $<TARGET_OBJECTS:cppgc_base>
)
target_config(cppgc_unittests
  PRIVATE
  v8_features
  v8_disable_exceptions
  external_config
  internal_config_base
  )
target_link_libraries(cppgc_unittests
  PRIVATE
    v8_libbase
    gmock gtest
  )
add_dependencies(cppgc_unittests v8_dump_build_config)

# Skip unittests_sources as these comprise the entire executable. Instead
# make them sources for unittests
add_executable(unittests)
target_sources(unittests
  PRIVATE
    ${D}/../../test/common/assembler-tester.h
    ${D}/../../test/common/wasm/wasm-macro-gen.h
    ${D}/../../testing/gmock-support.h
    ${D}/../../testing/gtest-support.h
    ${D}/api/access-check-unittest.cc
    ${D}/api/exception-unittest.cc
    ${D}/api/interceptor-unittest.cc
    ${D}/api/isolate-unittest.cc
    ${D}/api/remote-object-unittest.cc
    ${D}/api/resource-constraints-unittest.cc
    ${D}/api/v8-object-unittest.cc
    ${D}/asmjs/asm-scanner-unittest.cc
    ${D}/asmjs/asm-types-unittest.cc
    ${D}/base/address-region-unittest.cc
    ${D}/base/atomic-utils-unittest.cc
    ${D}/base/bits-unittest.cc
    ${D}/base/cpu-unittest.cc
    ${D}/base/division-by-constant-unittest.cc
    ${D}/base/flags-unittest.cc
    ${D}/base/functional-unittest.cc
    ${D}/base/ieee754-unittest.cc
    ${D}/base/iterator-unittest.cc
    ${D}/base/logging-unittest.cc
    ${D}/base/macros-unittest.cc
    ${D}/base/ostreams-unittest.cc
    ${D}/base/platform/condition-variable-unittest.cc
    ${D}/base/platform/mutex-unittest.cc
    ${D}/base/platform/platform-unittest.cc
    ${D}/base/platform/semaphore-unittest.cc
    ${D}/base/platform/time-unittest.cc
    ${D}/base/region-allocator-unittest.cc
    ${D}/base/sys-info-unittest.cc
    ${D}/base/template-utils-unittest.cc
    ${D}/base/threaded-list-unittest.cc
    ${D}/base/utils/random-number-generator-unittest.cc
    ${D}/base/vlq-base64-unittest.cc
    ${D}/codegen/code-stub-assembler-unittest.cc
    ${D}/codegen/code-stub-assembler-unittest.h
    ${D}/codegen/register-configuration-unittest.cc
    ${D}/codegen/source-position-table-unittest.cc
    ${D}/compiler-dispatcher/compiler-dispatcher-unittest.cc
    ${D}/compiler-dispatcher/optimizing-compile-dispatcher-unittest.cc
    ${D}/compiler/backend/instruction-selector-unittest.cc
    ${D}/compiler/backend/instruction-selector-unittest.h
    ${D}/compiler/backend/instruction-sequence-unittest.cc
    ${D}/compiler/backend/instruction-sequence-unittest.h
    ${D}/compiler/backend/instruction-unittest.cc
    ${D}/compiler/branch-elimination-unittest.cc
    ${D}/compiler/bytecode-analysis-unittest.cc
    ${D}/compiler/checkpoint-elimination-unittest.cc
    ${D}/compiler/common-operator-reducer-unittest.cc
    ${D}/compiler/common-operator-unittest.cc
    ${D}/compiler/compiler-test-utils.h
    ${D}/compiler/constant-folding-reducer-unittest.cc
    ${D}/compiler/control-equivalence-unittest.cc
    ${D}/compiler/control-flow-optimizer-unittest.cc
    ${D}/compiler/dead-code-elimination-unittest.cc
    ${D}/compiler/decompression-optimizer-unittest.cc
    ${D}/compiler/diamond-unittest.cc
    ${D}/compiler/effect-control-linearizer-unittest.cc
    ${D}/compiler/graph-reducer-unittest.cc
    ${D}/compiler/graph-reducer-unittest.h
    ${D}/compiler/graph-trimmer-unittest.cc
    ${D}/compiler/graph-unittest.cc
    ${D}/compiler/graph-unittest.h
    ${D}/compiler/int64-lowering-unittest.cc
    ${D}/compiler/js-call-reducer-unittest.cc
    ${D}/compiler/js-create-lowering-unittest.cc
    ${D}/compiler/js-intrinsic-lowering-unittest.cc
    ${D}/compiler/js-native-context-specialization-unittest.cc
    ${D}/compiler/js-operator-unittest.cc
    ${D}/compiler/js-typed-lowering-unittest.cc
    ${D}/compiler/linkage-tail-call-unittest.cc
    ${D}/compiler/load-elimination-unittest.cc
    ${D}/compiler/loop-peeling-unittest.cc
    ${D}/compiler/machine-operator-reducer-unittest.cc
    ${D}/compiler/machine-operator-unittest.cc
    ${D}/compiler/node-cache-unittest.cc
    ${D}/compiler/node-matchers-unittest.cc
    ${D}/compiler/node-properties-unittest.cc
    ${D}/compiler/node-test-utils.cc
    ${D}/compiler/node-test-utils.h
    ${D}/compiler/node-unittest.cc
    ${D}/compiler/opcodes-unittest.cc
    ${D}/compiler/persistent-unittest.cc
    ${D}/compiler/redundancy-elimination-unittest.cc
    ${D}/compiler/regalloc/live-range-unittest.cc
    ${D}/compiler/regalloc/move-optimizer-unittest.cc
    ${D}/compiler/regalloc/register-allocator-unittest.cc
    ${D}/compiler/schedule-unittest.cc
    ${D}/compiler/scheduler-rpo-unittest.cc
    ${D}/compiler/scheduler-unittest.cc
    ${D}/compiler/simplified-lowering-unittest.cc
    ${D}/compiler/simplified-operator-reducer-unittest.cc
    ${D}/compiler/simplified-operator-unittest.cc
    ${D}/compiler/state-values-utils-unittest.cc
    ${D}/compiler/typed-optimization-unittest.cc
    ${D}/compiler/typer-unittest.cc
    ${D}/compiler/value-numbering-reducer-unittest.cc
    ${D}/compiler/zone-stats-unittest.cc
    ${D}/date/date-cache-unittest.cc
    ${D}/diagnostics/eh-frame-iterator-unittest.cc
    ${D}/diagnostics/eh-frame-writer-unittest.cc
    ${D}/execution/microtask-queue-unittest.cc
    ${D}/heap/barrier-unittest.cc
    ${D}/heap/bitmap-test-utils.h
    ${D}/heap/bitmap-unittest.cc
    ${D}/heap/code-object-registry-unittest.cc
    ${D}/heap/embedder-tracing-unittest.cc
    ${D}/heap/gc-idle-time-handler-unittest.cc
    ${D}/heap/gc-tracer-unittest.cc
    ${D}/heap/heap-controller-unittest.cc
    ${D}/heap/heap-unittest.cc
    ${D}/heap/item-parallel-job-unittest.cc
    ${D}/heap/list-unittest.cc
    ${D}/heap/local-heap-unittest.cc
    ${D}/heap/marking-unittest.cc
    ${D}/heap/marking-worklist-unittest.cc
    ${D}/heap/memory-reducer-unittest.cc
    ${D}/heap/object-stats-unittest.cc
    ${D}/heap/off-thread-factory-unittest.cc
    ${D}/heap/safepoint-unittest.cc
    ${D}/heap/slot-set-unittest.cc
    ${D}/heap/spaces-unittest.cc
    ${D}/heap/unmapper-unittest.cc
    ${D}/heap/worklist-unittest.cc
    ${D}/interpreter/bytecode-array-builder-unittest.cc
    ${D}/interpreter/bytecode-array-iterator-unittest.cc
    ${D}/interpreter/bytecode-array-random-iterator-unittest.cc
    ${D}/interpreter/bytecode-array-writer-unittest.cc
    ${D}/interpreter/bytecode-decoder-unittest.cc
    ${D}/interpreter/bytecode-node-unittest.cc
    ${D}/interpreter/bytecode-operands-unittest.cc
    ${D}/interpreter/bytecode-register-allocator-unittest.cc
    ${D}/interpreter/bytecode-register-optimizer-unittest.cc
    ${D}/interpreter/bytecode-source-info-unittest.cc
    ${D}/interpreter/bytecode-utils.h
    ${D}/interpreter/bytecodes-unittest.cc
    ${D}/interpreter/constant-array-builder-unittest.cc
    ${D}/interpreter/interpreter-assembler-unittest.cc
    ${D}/interpreter/interpreter-assembler-unittest.h
    ${D}/libplatform/default-job-unittest.cc
    ${D}/libplatform/default-platform-unittest.cc
    ${D}/libplatform/default-worker-threads-task-runner-unittest.cc
    ${D}/libplatform/task-queue-unittest.cc
    ${D}/libplatform/worker-thread-unittest.cc
    ${D}/logging/counters-unittest.cc
    ${D}/numbers/bigint-unittest.cc
    ${D}/numbers/conversions-unittest.cc
    ${D}/objects/backing-store-unittest.cc
    ${D}/objects/object-unittest.cc
    ${D}/objects/osr-optimized-code-cache-unittest.cc
    ${D}/objects/value-serializer-unittest.cc
    ${D}/objects/weakarraylist-unittest.cc
    ${D}/parser/ast-value-unittest.cc
    ${D}/parser/preparser-unittest.cc
    ${D}/profiler/strings-storage-unittest.cc
    ${D}/regress/regress-crbug-1041240-unittest.cc
    ${D}/regress/regress-crbug-1056054-unittest.cc
    ${D}/regress/regress-crbug-938251-unittest.cc
    ${D}/run-all-unittests.cc
    ${D}/strings/char-predicates-unittest.cc
    ${D}/strings/unicode-unittest.cc
    ${D}/tasks/background-compile-task-unittest.cc
    ${D}/tasks/cancelable-tasks-unittest.cc
    ${D}/test-helpers.cc
    ${D}/test-helpers.h
    ${D}/test-utils.cc
    ${D}/test-utils.h
    ${D}/torque/earley-parser-unittest.cc
    ${D}/torque/ls-json-unittest.cc
    ${D}/torque/ls-message-unittest.cc
    ${D}/torque/ls-server-data-unittest.cc
    ${D}/torque/torque-unittest.cc
    ${D}/torque/torque-utils-unittest.cc
    ${D}/utils/allocation-unittest.cc
    ${D}/utils/detachable-vector-unittest.cc
    ${D}/utils/locked-queue-unittest.cc
    ${D}/utils/utils-unittest.cc
    ${D}/utils/vector-unittest.cc
    ${D}/wasm/control-transfer-unittest.cc
    ${D}/wasm/decoder-unittest.cc
    ${D}/wasm/function-body-decoder-unittest.cc
    ${D}/wasm/leb-helper-unittest.cc
    ${D}/wasm/loop-assignment-analysis-unittest.cc
    ${D}/wasm/module-decoder-unittest.cc
    ${D}/wasm/streaming-decoder-unittest.cc
    ${D}/wasm/wasm-code-manager-unittest.cc
    ${D}/wasm/wasm-compiler-unittest.cc
    ${D}/wasm/wasm-macro-gen-unittest.cc
    ${D}/wasm/wasm-module-builder-unittest.cc
    ${D}/wasm/wasm-module-sourcemap-unittest.cc
    ${D}/zone/zone-allocator-unittest.cc
    ${D}/zone/zone-chunk-list-unittest.cc
    ${D}/zone/zone-unittest.cc
    $<${is-arm}:
      ${D}/assembler/turbo-assembler-arm-unittest.cc
      ${D}/compiler/arm/instruction-selector-arm-unittest.cc
    >
    $<${is-arm64}:
      ${D}/assembler/turbo-assembler-arm64-unittest.cc
      ${D}/compiler/arm64/instruction-selector-arm64-unittest.cc
    >
    $<${is-ia32}:
      ${D}/assembler/turbo-assembler-ia32-unittest.cc
      ${D}/compiler/ia32/instruction-selector-ia32-unittest.cc
    >
    $<$<OR:${is-mips},${is-mipsel}>:
      ${D}/assembler/turbo-assembler-mips-unittest.cc
      ${D}/compiler/mips/instruction-selector-mips-unittest.cc
    >
    $<$<OR:${is-mips64},${is-mips64el}>:
      ${D}/assembler/turbo-assembler-mips64-unittest.cc
      ${D}/compiler/mips64/instruction-selector-mips64-unittest.cc
    >
    $<${is-ia32}:
      ${D}/assembler/turbo-assembler-x64-unittest.cc
      ${D}/compiler/x64/instruction-selector-x64-unittest.cc
      ${D}/wasm/trap-handler-x64-unittest.cc
    >
    $<$<OR:${is-ppc},${is-ppc64}>:
    ${D}/assembler/turbo-assembler-ppc-unittest.cc
    ${D}/compiler/ppc/instruction-selector-ppc-unittest.cc
    >
    $<$<OR:${is-s390},${is-s390x}>:
    ${D}/assembler/turbo-assembler-s390-unittest.cc
    ${D}/compiler/s390/instruction-selector-s390-unittest.cc
    >
    $<${is-posix}:
      ${D}/wasm/trap-handler-posix-unittest.cc
    >
    $<${is-win}:
      ${D}/wasm/trap-handler-win-unittest.cc
    >
  $<TARGET_OBJECTS:wasm_test_common>
  $<TARGET_OBJECTS:v8_cppgc_shared>
  $<TARGET_OBJECTS:cppgc_base>
  )
target_config(unittests
  PRIVATE
    v8_features
    v8_disable_exceptions
    cppgc_base_config
    external_config
    internal_config_base
  )
target_compile_options(unittests
  PRIVATE
    $<${is-clang}:-Wno-narrowing>
  )
target_link_libraries(unittests PRIVATE
  cppgc_unittests_sources
  #unittests_sources
  #v8_for_testing
  torque_ls_base
  v8_initializers
  v8_base_without_compiler
  v8_compiler
  v8_libbase
  v8_libplatform
  v8_snapshot
  #crdtp_test
  #gmock gtest
  )
add_dependencies(unittests v8_dump_build_config)

