name: v8-cmake

on:
  push:
  pull_request:
    paths:
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'v8/**'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-16.04, ubuntu-18.04, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: cmake -E make_directory ${{runner.workspace}}/build
      # Note: `cmake -B ${{runner.workspace}}/build` needs
      # cmake 3.13 but Ubuntu 16.04 comes with cmake 3.12.
      - name: configure
        run: cmake ${{runner.workspace}}/v8-cmake
        working-directory: ${{runner.workspace}}/build
      - name: build
        run: cmake --build ${{runner.workspace}}/build -j 2
      - name: test
        if: matrix.os != 'windows-latest'
        run: ${{runner.workspace}}/build/d8 -e 42
      - name: test-windows
        if: matrix.os == 'windows-latest'
        run: |
          ${{runner.workspace}}/build/Debug/d8 -e 42
        shell: powershell
